# Generated by Django 2.1.8 on 2024-09-16 13:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('edit_auth', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssetForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=254, null=True)),
                ('middle', models.CharField(blank=True, max_length=254, null=True)),
                ('last', models.CharField(blank=True, max_length=254, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('maiden', models.CharField(blank=True, max_length=254, null=True)),
                ('veteren', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_form',
            },
        ),
        migrations.CreateModel(
            name='MasterGeom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc_fid', models.IntegerField()),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=11, max_digits=18, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=11, max_digits=18, null=True)),
                ('first', models.CharField(blank=True, max_length=254, null=True)),
                ('middle', models.CharField(blank=True, max_length=254, null=True)),
                ('last', models.CharField(blank=True, max_length=254, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('maiden', models.CharField(blank=True, max_length=254, null=True)),
                ('veteren', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('addition', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('lot', models.CharField(blank=True, max_length=50, null=True)),
                ('plot', models.CharField(blank=True, max_length=50, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'master_geom',
            },
        ),
    ]
