# Generated by Django 2.1.8 on 2024-09-26 15:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_assetform_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc_fid', models.IntegerField()),
                ('first', models.CharField(blank=True, max_length=254, null=True)),
                ('middle', models.CharField(blank=True, max_length=254, null=True)),
                ('last', models.CharField(blank=True, max_length=254, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('maiden', models.CharField(blank=True, max_length=254, null=True)),
                ('is_veteran', models.BooleanField(default=False)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('addition', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('lot', models.CharField(blank=True, max_length=50, null=True)),
                ('plot', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plot_form',
            },
        ),
        migrations.DeleteModel(
            name='AssetForm',
        ),
        migrations.RenameField(
            model_name='mastergeom',
            old_name='wkb_geometry',
            new_name='geom',
        ),
        migrations.RemoveField(
            model_name='mastergeom',
            name='first',
        ),
        migrations.RemoveField(
            model_name='mastergeom',
            name='last',
        ),
        migrations.RemoveField(
            model_name='mastergeom',
            name='maiden',
        ),
        migrations.RemoveField(
            model_name='mastergeom',
            name='middle',
        ),
        migrations.RemoveField(
            model_name='mastergeom',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='mastergeom',
            name='veteren',
        ),
        migrations.AddField(
            model_name='mastergeom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastergeom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
