# Generated by Django 2.1.8 on 2024-10-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20240926_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotform',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='plotform',
            old_name='last',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='plotform',
            old_name='maiden',
            new_name='maiden_name',
        ),
        migrations.RenameField(
            model_name='plotform',
            old_name='middle',
            new_name='middle_name',
        ),
    ]
