# Generated by Django 2.1.8 on 2024-10-21 17:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20241004_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='CemeteryPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc_fid', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_veteran', models.BooleanField(default=False)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('addition', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('lot', models.CharField(blank=True, max_length=50, null=True)),
                ('plot', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cemetery_plot',
            },
        ),
        migrations.DeleteModel(
            name='PlotForm',
        ),
    ]
