# Generated by Django 2.1.8 on 2024-12-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20241219_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cemeteryplot',
            name='master_geom',
        ),
        migrations.AddField(
            model_name='mastergeom',
            name='cemetery_plot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geom', to='main_app.CemeteryPlot'),
        ),
    ]
