# Generated by Django 2.1.8 on 2024-12-20 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20241219_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CemeteryPlotForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_veteran', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cemetery_plot_form',
            },
        ),
        migrations.RemoveField(
            model_name='cemeteryplot',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mastergeom',
            name='cemetery_plot',
        ),
        migrations.DeleteModel(
            name='CemeteryPlot',
        ),
        migrations.AddField(
            model_name='cemeteryplotform',
            name='geom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cemetery_plot_form', to='main_app.MasterGeom'),
        ),
    ]
